const dataGame = {
	scene:document.querySelector('#scene'),
	speed:30,
	gravity:8,
	decor:{
		items:{
			size:{h:32,w:32},
			src:'medias/img/decors_herbe32-X6Y3.jpg',
			delta:{y:3,x:6}
		},
		panels:{
			name:'panel',
			nb:4,
			size:{
				w:320,
				h:64
			}
		},
		animePosition:8
	},
	perso:{
		size:{h:40,w:40},
		src:'medias/img/hero32-X3Y1.png',
		delta:{y:1,x:3},
		startPos:{y:64,x:192},
		speed:0.35,
		jumpLimit:128,
		key:32
	},
	enemy:{
		size:{h:32,w:32},
		src:'medias/img/rocher32-X2Y1.png',
		delta:{y:1,x:2},
		animePosition:8
	}
}

const data = {
	scene:document.querySelector('#scene'),
	speed:30,
	gravity:8,
	decor:{
		items:{
			size:{h:32,w:32},
			src:'medias/img/decors_herbe32-X6Y3.jpg',
			delta:{y:3,x:6}
		},
		panels:{
			name:'panel',
			nb:4,
			size:{
				w:320,
				h:64
			}
		},
		animePosition:8
	},
	perso:{
		size:{h:40,w:40},
		src:'medias/img/hero32-X3Y1.png',
		delta:{y:1,x:3},
		startPos:{y:64,x:192},
		speed:0.35,
		jumpLimit:128,
		key:32
	},
	enemy:{
		size:{h:32,w:32},
		src:'medias/img/rocher32-X2Y1.png',
		delta:{y:1,x:2},
		animePosition:8
	}
}